### ISSUE TITLE
What data types can I work with?

### ISSUE THREAD

**Issue by colesnicov** [chrysn/embedvm#1]
Hello. A very interesting project, it certainly took up a lot of your time. But I want to ask: I haven't found any documentation for this, so I can't figure out how to work with arrays and strings or with numbers with a decimal point (floats)? Thank you

**Comment by chrysn** [comment]
If I remember correctly, the data types it can work with are integers (implemented in embedvm's 16-bit integers) as well as signed and unsigned 8-bit integers and statically sized lists of single types of primitives.

As the commit dates probably give away, this is unmaintained these days, and likely only useful for curiosity's sake, or as inspiration when doing something similar with more modern tools.
